server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inha_nav?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root        # ← 네 MySQL 계정
    password: Inhatc2025!@      # ← 네 비밀번호
  jpa:
    hibernate:
      ddl-auto: none      # 이미 테이블 만들어뒀으니 'none' 권장 (update도 가능)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 개발용 CORS 허용(React dev 서버)
app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"
